### ISSUE TITLE
Row deletion in event templates is non-reversible

### ISSUE THREAD

**Issue by ousabd** [dhammaorg/matta-nuu#13]
Unlike other edits which require a click on the Save button, deleting a row in an event template is automatically saved and can not be reverted.

**Comment by seballot** [comment]
I cannot reproduce...

[Capture vidéo du 2024-09-25 20-01-41.webm](https://github.com/user-attachments/assets/511582ee-8268-450a-a4c3-94ea6979929a)

**Comment by ousabd** [comment]
Me neither! :open_mouth:
