### ISSUE TITLE
Inventory does not open

### ISSUE THREAD

**Issue by ousabd** [dhammaorg/matta-nuu#15]
After I click on Start, I have a green popup displaying "Successfully created" but nothing else appears (apart from the menu and session tabs). Same when I try to edit an existing inventory from the Overview.

Tested on: Firefox, Chrome, VIvaldi (based on Chromium)

Priority: **very high** (faut m'aider là sinon je ne vais jamais pouvoir convaincre JF :)

**Comment by seballot** [comment]
yop ! t'es sur quel compte et quelle session? car chez moi ça marche bien...

**Comment by ousabd** [comment]
Sur coordinateur-cuisine@mahi.dhamma.org
Session : "EN COURS"

Je me suis déconnecté / reconnecté plusieurs fois. Parfois j'ai ça :
![image](https://github.com/user-attachments/assets/5a11a316-68da-42c5-ac7d-f414d8378f12)
Puius ça :
![image](https://github.com/user-attachments/assets/bc6573bc-5849-48b3-b966-73181fa8e4c2)

Puis plus rien.

Et là je ne vois même plus rien dans les stocks e la session EN COURS, bien que le schedule soit correctement programmé...
