### ISSUE TITLE
Need more space in prints / exports of orders

### ISSUE THREAD

**Issue by ousabd** [dhammaorg/matta-nuu#16]
Packaging names that appear on orders can be quite long (brand + model + packaging + ...).
Can we decrease the margins and/or decrease slightly the font of the Product column.

**Comment by seballot** [comment]
I would prefer not touch the margin and font, but allow the text to wrap to a new line if it's too long

How to reproduce : 

- create an order
- Add a product if none is there
- Click on the product name to edit it and put something very long
![image](https://github.com/user-attachments/assets/e35d6650-6f51-4b5c-bfd4-1961f16d9d81)
- click print
![image](https://github.com/user-attachments/assets/92fc0dd8-553b-4145-a457-efdb0cae6745)

technical : you can either try to replace the input by a textarea with dynamic height. Or to replace the input by a standard div, and use the input only when the user click on the row to edit the product name
