### ISSUE TITLE
Franco de port et réduction

### ISSUE THREAD

**Issue by Focus-Pacifique** [dhammaorg/matta-nuu#26]
Nathalie et Oussama me font remonter ceci.

Ce serait intéressant de faire apparaître pour chaque fournisseur le franco de port (pour ajuster la commande si besoin pour en bénéficier).
Pour Celnat, on a aussi des réductions plus importante à partir de certains seuils de commande (+5% de réduc entre 800 et 1000 euros, +8% de réduc à partir de 1000 euros), cette info pourrait aussi apparaître dans la commande.

**Comment by seballot** [comment]
c'est déjà possible, pour chaque producteur y'a une "description" qui apparait en haut de la commande, et qui n'est pas imprimée
