### ISSUE TITLE
Modifier la valeur du stock théorique avec alertes

### ISSUE THREAD

**Issue by Vichearith** [dhammaorg/matta-nuu#3]
Description :
Lors de l'inventaire, garder la valeur du stock théorique et alerter l'utilisateur si un écart significatif est détecté par rapport au dernier inventaire.

Tâches :
- Ajouter une option lors de la création de la session pour choisir si on veut des alertes ou non.
- Permettre la fixation du pourcentage d'alerte dans les paramètres du compte et de la session.

Priorité :

**Comment by seballot** [comment]
J'ai fait la modif
