### ISSUE TITLE
Inventaire en mode semi-synchronisé

### ISSUE THREAD

**Issue by Vichearith** [dhammaorg/matta-nuu#4]
Description :
Améliorer l'inventaire pour que les données soient sauvegardées de manière "semi-synchronisée", envoyant seulement les données modifiées.

Tâches :
- Implémenter une logique pour envoyer seulement les données modifiées lors de la sauvegarde de l'inventaire.
- Ajouter un système d'alerte si deux personnes travaillent simultanément sur l'inventaire, sur une même zone de produits

Priorité : Haute

**Comment by seballot** [comment]
En fait hier après la réunion on s'est rendu compte que il y avait déjà un moyen de faire des inventaires en parallele : il suffit que chaque personne crée son propre "Inventaire" avec le bouton "+ inventaire". ainsi lors de la sauvegarde, chaque inventaire sera indépendant, mais toutes leur données seront prises en compte pour les stock

Du coup soit on garde cette issue avec priorité basse ou normale, soit carrément on l'oublie
